name : first workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name : Print Welcome Message
        run : echo "Welcome to my Workflow! :) "

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name : List Repo's files
        run:  ls -la
