name : first workflow

on:
  push:
    branches: 
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    
    steps:
      - name : Print Welcome Message
        run : echo "Welcome to my Workflow! :) "

      - name : Checkout Reposotory
        uses : actions/checkout@v7.0.1

      - name : List Repo's files
        run:  ls -la
